name: "Docker Build and Push"
description: "Docker build and pushing to ECR Registry ..."
inputs:
  aws-access-key-id:
    description: 'AWS Access Key Id'
    required: true

  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true

  aws-region:
    description: 'AWS Resource Region'
    required: true

  bit-token:
    description: 'BIT Access Token'
    required: true

  pat-token:
    description: 'Github PAT Token'
    required: true

  # sha-length:
  #   description: 'Github PAT Token'
  #   required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Update .npmrc
      run: |
          echo -e "\n" >> .npmrc
          echo -e "//node.bit.dev/:_authToken=${{ inputs.bit-token }}" >> .npmrc
          echo -e "//npm.pkg.github.com/:_authToken=${{ inputs.pat-token }}" >> .npmrc 
      shell: bash
    

    