name: "Docker Build and Push"
description: "Docker build and pushing to ECR Registry ..."
inputs:
  aws-access-key-id:
    description: 'AWS Access Key Id'
    required: true

  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true

  aws-region:
    description: 'AWS Resource Region'
    required: true
  # issue_title:
  #   description: 'Zap Scan Report title'
  #   required: true 
  # fail_action:
  #   description: 'Apply fail action on failure'
  #   required: true
  # rules_file_name:
  #   description: 'The filepath of the zap rules file'
  #   required: true

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7
          
    - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ inputs.aws-access-key-id }}
          aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}
    # - name: ZAP Scan
    #   uses: zaproxy/action-api-scan@v0.1.0
    #   with:
    #     target: ${{ inputs.target }} 
    #     issue_title: ${{ inputs.issue_title }} 
    #     fail_action: ${{ inputs.fail_action }} 
    #     rules_file_name: ${{ inputs.rules_file_name }} 
    